CREATE TABLE COUNTRY (
  Code CHAR(3) DEFAULT '',
  Name CHAR(52) DEFAULT '',
  Continent CHAR(13) DEFAULT 'Asia',
  Region CHAR(26) DEFAULT '',
  SurfaceArea NUMBER(10,2) DEFAULT '0.00',
  IndepYear NUMBER(6) DEFAULT NULL,
  Population NUMBER(11) DEFAULT '0',
  LifeExpectancy NUMBER(3,1) DEFAULT NULL,
  GNP NUMBER(10,2) DEFAULT NULL,
  GNPOld NUMBER(10,2) DEFAULT NULL,
  LocalName CHAR(45) DEFAULT '',
  GovernmentForm CHAR(45) DEFAULT '',
  HeadOfState CHAR(60) DEFAULT NULL,
  Capital NUMBER(11) DEFAULT NULL,
  Code2 CHAR(2) DEFAULT '',
  CONSTRAINT Country_Code_PK Primary Key(Code));

CREATE TABLE COUNTRYLANGUAGE (
  CountryCode CHAR(3) DEFAULT '',
  Language CHAR(30) DEFAULT '',
  IsOfficial CHAR(1) DEFAULT 'F',
  Percentage NUMBER(4,1) DEFAULT '0.0',
  CONSTRAINT CountryCode_Language_PK PRIMARY KEY (CountryCode),
  CONSTRAINT CountryLanguage_FK FOREIGN KEY (CountryCode) REFERENCES COUNTRY (Code));
);


CREATE TABLE CITY (
  ID NUMBER(11),
  Name CHAR(35),
  CountryCode CHAR(3),
  District CHAR(20),
  Population NUMBER(11),
  CONSTRAINT CITY_ID_PK Primary Key(ID),
  CONSTRAINT CITY_ID_FK Foreign Key(CountryCode) References COUNTRY(Code)
);

DROP TABLE CITY;
DROP TABLE COUNTRYLANGUAGE;
DROP TABLE COUNTRY;

CREATE INDEX "FK" ON  "CITY" ("CountryCode");


